name: resilio-sync

services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - resilio-config:/config
      - /home/ubuntu/notes:/sync/notes
    ports:
      - "8888:8888"
      - "55555:55555"
    networks:
      - resilio-sync

volumes:
  resilio-config:
    driver: local

networks:
  resilio-sync:
    driver: bridge
