name: audiobookshelf

services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    environment:
      AUDIOBOOKSHELF_UID: 1000
      AUDIOBOOKSHELF_GID: 1000
    volumes:
      - audiobookshelf-config:/config
      - audiobookshelf-books:/audiobooks:ro
    ports:
      - "13378:80"
    networks:
      - audiobookshelf

volumes:
  audiobookshelf-config:
    driver: local
  audiobookshelf-books:
    external: true

networks:
  audiobookshelf:
    driver: bridge
