name: homeassistant

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2024.12.3
    container_name: homeassistant
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ha-config:/config
      - ./configuration.yaml:/config/configuration.yaml
    privileged: true
    networks:
      - homeassistant

volumes:
  ha-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/tank/shared/homeassistant/config

networks:
  homeassistant:
    driver: bridge
