name: navidrome

services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    environment:
      ND_LOGFORMAT: json
      ND_LOGFRAME: "false"
      ND_BASEURL: ""
    volumes:
      - navidrome-config:/data
      - navidrome-music:/music:ro
    networks:
      - navidrome

volumes:
  navidrome-config:
    driver: local
  navidrome-music:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/tank/shared/navidrome

networks:
  navidrome:
    driver: bridge
