version: '3.8'

services:
  blocky:
    image: spx01/blocky:latest
    container_name: blocky
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config.yml:/app/config.yml
    networks:
      - infra
      - dokploy-network

networks:
  infra:
    driver: bridge
  dokploy-network:
    external: true
