name: jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      JELLYFIN_DATA_DIR: /config
      JELLYFIN_CACHE_DIR: /cache
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - jellyfin-media:/media:ro
    ports:
      - "8096:8096"
    networks:
      - jellyfin
    devices:
      - /dev/dri:/dev/dri

volumes:
  jellyfin-config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.68.19,vers=4,soft,timeo=180,tcp,rw,nolock
      device: ":/mnt/tank/shared/jellyfin/config"
  jellyfin-cache:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.68.19,vers=4,soft,timeo=180,tcp,rw,nolock
      device: ":/mnt/tank/shared/jellyfin/cache"
  jellyfin-media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.68.19,vers=4,soft,timeo=180,tcp,rw,nolock
      device: ":/mnt/tank/shared/jellyfin/media"

networks:
  jellyfin:
    driver: bridge
