name: jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.11
    container_name: jellyfin
    restart: unless-stopped
    environment:
      JELLYFIN_DATA_DIR: /config
      JELLYFIN_CACHE_DIR: /cache
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - jellyfin-media:/media
    networks:
      - jellyfin
    devices:
      - /dev/dri:/dev/dri

volumes:
  jellyfin-config:
  jellyfin-cache:
  jellyfin-media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/tank/shared/jellyfin/media

networks:
  jellyfin:
    driver: bridge
