services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - default

volumes:
  minio-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.68.19,vers=4,soft,timeo=180,tcp,rw,nolock
      device: ':/mnt/tank/shared/minio'
