name: gtnh

services:
  gtnh:
    image: itzg/minecraft-server:java21
    container_name: gtnh
    restart: unless-stopped
    pull_policy: missing
    tty: true
    stdin_open: true
    network_mode: "service:gtnh-tailscale"
    depends_on:
      - gtnh-tailscale
    environment:
      EULA: "TRUE"
      TYPE: GTNH
      GTNH_PACK_VERSION: "2.9.0-RC-1"
      SKIP_GTNH_UPDATE_CHECK: "true"
      MEMORY: "6G"
      INIT_MEMORY: "6G"
      MAX_MEMORY: "6G"
      JVM_OPTS: "-Dfml.readTimeout=180 @java9args.txt -Dfml.queryResult=confirm"
      MOTD: "GT:New Horizons"
      DIFFICULTY: "hard"
      ENABLE_COMMAND_BLOCK: "true"
      SPAWN_PROTECTION: 1
      VIEW_DISTANCE: 8
      MODE: "0"
      LEVEL_TYPE: "BIOMESOP"
      LEVEL: "OmniSlop"
      ALLOW_FLIGHT: "TRUE"
      DUMP_SERVER_PROPERTIES: "TRUE"
      CREATE_CONSOLE_IN_PIPE: "true"
      WHITELIST: |
          Kajtek8
      OPS: |
          IguruSama
    volumes:
      - gtnh-data:/data

  gtnh-tailscale:
    image: tailscale/tailscale:latest
    container_name: gtnh-tailscale
    hostname: gtnh
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - gtnh-tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY_GTNH}
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: "false"

volumes:
  gtnh-data:
  gtnh-tailscale-state: